name: Goal Bots

on:
  schedule:
    - cron: '0 12 * * *'  # 09:00 Brasil
    - cron: '0 13 * * *'  # 10:00 Brasil
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: |
          pip install -r requirements.txt

      - name: Run bots
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          BZ_API_KEY: ${{ secrets.BZ_API_KEY }}
        run: |
          HOUR=$(date +%H)

          if [ "$HOUR" -eq 12 ]; then
            python bot_free.py
            python vip_bot.py
          fi

          if [ "$HOUR" -eq 13 ]; then
            python report_bot.py
          fi
